[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyMaxRetries = 3

[service]
internal_port = 5000
name = "Pumpfunguard"

[database]
type = "mongodb"
plan = "free"
